### ISSUE TITLE
Can you put this on the App Store?

### ISSUE THREAD

**Issue by sargeant45** [istx25/pistachio#4]
I'd pay a couple bucks for it. Just wondering, although I'm not sure if you have a Developer Account.

**Comment by istx25** [comment]
@sargeant45: No problem about the developer account, I have multiple - but I don't know if I want to put Pistachio to the app store. I originally started this project because I wanted a hackable and beautiful Github client for iOS that would eventually bring together a community that would collaboratively work together to make Pistachio better. I will more thoroughly consider this when v1 is closer to completion.

If you'd like to support this project (and me), I would be ever so grateful if you tipped me through another platform (PayPal, Stripe, etc). I will also try to set up Gratipay with this project. :heart: :construction:
